services:
  - type: web
    name: jacom-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jacom-db
          property: connectionString
      - key: ENV
        value: production
