-- Insert Industries with JACOM business context
INSERT INTO Industry (id, name, slug, description, overview, challenges, trends, featured, image, createdAt, updatedAt) VALUES
('ind1', 'Management Consulting', 'management-consulting', 'Strategic consulting for digital transformation and business growth in Japan', 'JACOM provides comprehensive management consulting services focusing on digital transformation (DX), ESG initiatives, and PMO services. We support Japanese companies in developing growth strategies and navigating the evolving consulting market with expertise in AI, IoT, and system integration.', '["Digital transformation adoption", "ESG compliance and reporting", "Project management efficiency", "Generative AI integration", "Global expansion strategies"]', '["AI-driven consulting", "Sustainability focus", "Remote consulting models", "Data-driven decision making", "Cross-border collaboration"]', 1, 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800', NOW(), NOW()),

('ind2', 'Technology & IoT Solutions', 'technology-iot', 'IoT platform and electromechanical system integration services', 'JACOM specializes in IoT e-commerce platforms and electromechanical system integration. We provide innovative solutions for smart devices, system standardization, and engineering consulting for consumers and manufacturers. Our platform infrastructure enables low-cost system integration with secured IoT software applications.', '["System integration complexity", "IoT security standards", "Device interoperability", "Cost optimization", "Technology adoption barriers"]', '["Smart device proliferation", "Edge computing", "5G connectivity", "AI-powered automation", "Cloud-native architectures"]', 1, 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800', NOW(), NOW()),

('ind3', 'Hospitality & Tourism', 'hospitality-tourism', 'Recruitment and training services for hospitality professionals', 'Through our partnership with Nepal recruitment agencies, JACOM facilitates the deployment of qualified hospitality professionals to Japan. We provide comprehensive training including Japanese language proficiency (JLPT N3/N4), cultural orientation, and industry-specific technical skills for hotel services, culinary arts, and hospitality management.', '["Skilled labor shortage", "Cultural adaptation", "Language barriers", "Quality standards maintenance", "Visa and immigration processes"]', '["International workforce mobility", "Digital hospitality services", "Sustainable tourism", "Experience-driven services", "Health and safety protocols"]', 1, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800', NOW(), NOW()),

('ind4', 'IT Services & Software Development', 'it-services', 'Software development and IT professional recruitment for Japanese market', 'JACOM connects IT professionals with opportunities in Japan, focusing on software engineers, data scientists, and cybersecurity experts. We support J-Find visa holders and provide training in programming (Java, Python, C++), database management, and cloud computing to meet Japan\'s growing demand for digital talent.', '["Tech talent shortage", "Rapid technology evolution", "Cybersecurity threats", "Legacy system modernization", "Remote work infrastructure"]', '["AI and machine learning", "Cloud-first strategies", "DevOps automation", "Low-code platforms", "Quantum computing readiness"]', 0, 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800', NOW(), NOW()),

('ind5', 'Manufacturing & Industry 4.0', 'manufacturing', 'Smart factory solutions and industrial automation consulting', 'JACOM delivers Industry 4.0 transformation through IoT integration, predictive maintenance, and smart factory design. We specialize in production management, quality control systems, and mechanical design with expertise in sensors, actuators, robotics, and embedded systems for manufacturing excellence.', '["Supply chain disruptions", "Automation investment costs", "Skills gap in workforce", "Quality control consistency", "Sustainability requirements"]', '["Smart factories", "Digital twins", "Predictive maintenance", "Collaborative robots", "Sustainable manufacturing"]', 0, 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800', NOW(), NOW()),

('ind6', 'Education & Training', 'education-training', 'Professional development and technical training programs', 'JACOM offers customized training programs including web development bootcamps, technical skills training, and professional certifications. We provide both online live sessions and face-to-face training in HTML, CSS, JavaScript, React, and Node.js, supporting career development for international professionals seeking opportunities in Japan.', '["Digital literacy gaps", "Curriculum relevance", "Student engagement", "Certification standards", "Access to quality education"]', '["EdTech platforms", "Hybrid learning models", "Micro-credentials", "Personalized learning paths", "Industry-aligned curricula"]', 0, 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800', NOW(), NOW()),

('ind7', 'Energy & Utilities', 'energy-utilities', 'Renewable energy systems and smart grid solutions', 'JACOM provides renewable energy consulting including solar and wind power generation equipment design, VPP and EMS system innovation, and smart grid infrastructure. We specialize in energy management systems, remote monitoring, and control automation for sustainable energy transition.', '["Grid modernization costs", "Renewable integration", "Energy storage solutions", "Regulatory compliance", "Asset optimization"]', '["Clean energy transition", "Smart grids", "Energy storage systems", "Carbon neutrality goals", "Distributed energy resources"]', 0, 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800', NOW(), NOW()),

('ind8', 'Real Estate & Infrastructure', 'real-estate-infrastructure', 'Smart building systems and infrastructure development', 'JACOM designs intelligent building systems including access control, security surveillance, electrical equipment, and utility systems. We provide comprehensive infrastructure solutions for hotels, hospitals, and commercial facilities with focus on energy efficiency, safety, and operational excellence.', '["Aging infrastructure", "Smart building integration", "Energy efficiency standards", "Security requirements", "Maintenance costs"]', '["Smart buildings", "Green construction", "IoT-enabled facilities", "Predictive maintenance", "Sustainable design"]', 0, 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800', NOW(), NOW()),

('ind9', 'Financial Services & Investment', 'financial-services', 'Financial advisory and investment consulting', 'JACOM offers financial consulting services including tax management, asset management, risk assessment, and investment policy development. We provide expertise in banking services, portfolio management, and ESG investment strategies to support business growth and financial sustainability.', '["Regulatory complexity", "Market volatility", "Digital disruption", "Risk management", "ESG compliance"]', '["Fintech innovation", "ESG investing", "Digital currencies", "Robo-advisory", "Open banking"]', 0, 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800', NOW(), NOW());
