-- Insert Services with JACOM business context
INSERT INTO Service (id, name, slug, description, overview, methodologies, tools, featured, image, status, createdAt, updatedAt) VALUES
('srv1', 'Digital Transformation & DX Consulting', 'digital-transformation', 'Comprehensive DX strategy and implementation for Japanese enterprises', 'JACOM provides end-to-end digital transformation consulting focusing on AI, IoT, and generative AI integration. We help Japanese companies navigate Industry 4.0 and achieve operational excellence through technology adoption.', '["Agile transformation", "Design thinking", "Lean methodology", "Change management"]', '["AI/ML platforms", "IoT systems", "Cloud infrastructure", "Data analytics tools"]', 1, 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800', 'published', NOW(), NOW()),

('srv2', 'IoT Platform & System Integration', 'iot-platform', 'IoT e-commerce platform and electromechanical system integration', 'Specialized IoT platform development and system integration services. We standardize smart device communication protocols and provide low-cost integration solutions for manufacturers and consumers.', '["System architecture design", "API integration", "Protocol standardization", "Security implementation"]', '["IoT sensors", "Edge computing", "5G networks", "Cloud platforms"]', 1, 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800', 'published', NOW(), NOW()),

('srv3', 'Recruitment & Training Services', 'recruitment-training', 'International workforce recruitment and professional training programs', 'Comprehensive recruitment services connecting Nepal and Japan for hospitality and IT professionals. Includes Japanese language training (JLPT N3/N4), cultural orientation, and technical skills development.', '["Candidate screening", "Skills assessment", "Cultural training", "Language proficiency"]', '["JLPT preparation", "Technical training platforms", "Virtual interviews", "Onboarding systems"]', 1, 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800', 'published', NOW(), NOW()),

('srv4', 'Smart Factory & Industry 4.0', 'smart-factory', 'Industrial automation and smart manufacturing solutions', 'Design and implementation of smart factory systems with IoT integration, predictive maintenance, and production optimization. Expertise in sensors, actuators, robotics, and embedded systems.', '["Factory automation", "Process optimization", "Quality control", "Predictive analytics"]', '["Industrial IoT", "Robotics", "SCADA systems", "MES platforms"]', 0, 'https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=800', 'published', NOW(), NOW()),

('srv5', 'Renewable Energy Systems', 'renewable-energy', 'Solar, wind power generation and smart grid solutions', 'Renewable energy consulting including equipment design, VPP and EMS system innovation, remote monitoring, and control automation for sustainable energy transition.', '["Energy assessment", "System design", "Grid integration", "Performance monitoring"]', '["Solar PV systems", "Wind turbines", "Energy storage", "Smart meters"]', 0, 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800', 'published', NOW(), NOW()),

('srv6', 'Smart Building & Infrastructure', 'smart-building', 'Intelligent building systems and security solutions', 'Design of smart building systems including access control, security surveillance, electrical equipment, and utility systems for hotels, hospitals, and commercial facilities.', '["Building automation", "Security design", "Energy management", "Facility optimization"]', '["Access control systems", "CCTV", "BMS platforms", "IoT sensors"]', 0, 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800', 'published', NOW(), NOW()),

('srv7', 'Web Development Training', 'web-development-training', 'Professional web development bootcamps and certifications', 'Comprehensive training programs in HTML, CSS, JavaScript, React, and Node.js. Both online live sessions and face-to-face training for career development in Japan.', '["Project-based learning", "Hands-on coding", "Portfolio development", "Job placement support"]', '["VS Code", "Git/GitHub", "React", "Node.js", "MongoDB"]', 0, 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800', 'published', NOW(), NOW()),

('srv8', 'Financial Advisory & Investment', 'financial-advisory', 'Tax management, asset management, and ESG investment consulting', 'Financial consulting services including tax management, asset management, risk assessment, and ESG investment strategies to support business growth and sustainability.', '["Financial planning", "Risk assessment", "Portfolio management", "ESG analysis"]', '["Financial modeling tools", "Risk management software", "Portfolio trackers", "ESG metrics"]', 0, 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800', 'published', NOW(), NOW()),

('srv9', 'Project Management Office (PMO)', 'pmo-services', 'PMO setup and project management consulting', 'Establish and optimize Project Management Offices for Japanese enterprises. Support for project planning, progress tracking, resource allocation, and risk management.', '["PMO framework", "Agile/Scrum", "Risk management", "Stakeholder management"]', '["Project management software", "Collaboration tools", "Reporting dashboards", "Resource planning"]', 0, 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800', 'published', NOW(), NOW());
